application:
  debug: True
  environment: 'dev'
  # Changing the network if you want to set up your own network and
  # directory server. This setting overrides any configured NETWORK
  # environment variable
  network: 'DOMAIN'
  trace_server: 127.0.0.1

dirserver:
  name: 'directoryserver'
  logfile: '/tmp/byoda-dir.log'
  # Connection string for the Postgresql server for PowerDNS
  dnsdb: "postgresql://<username>:<password>@<ip>/byodadns"
    root_dir: '/opt/byoda/dirserver'
  roles:
    - directory
  private_key_password: '<changeme>'

