FROM ubuntu:24.04

LABEL org.opencontainers.image.authors="steven@byoda.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8

ENV PYTHONPATH=/podserver/byoda-python
WORKDIR /podserver

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8000/api/v1/status || exit 1

###
### Byoda
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    byoda-python \
    /opt/byoda/byoda-python

COPY ./Pipfile ./Pipfile.lock /podserver/byoda-python/

RUN apt-get update && apt-get install -y \
       ubuntu-keyring \
       curl \
       ca-certificates \
       build-essential \
       python3 \
       python3-pip \
       python3-setuptools \
       libssl-dev \
       libffi-dev \
       python3-dev \
       pipenv \
       libpq-dev \
       libnng1 \
       sqlite3 \
       libaugeas0 \
       unzip \
       curl \
       git \
    && cd /podserver/byoda-python && pipenv install --verbose --deploy --ignore-pipfile && pipenv clean \
    && apt-get --yes remove build-essential \
    && apt-get --yes autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

COPY . byoda-python/

CMD cd /podserver/byoda-python \
    && pipenv run python3 -m gunicorn \
       -k uvicorn.workers.UvicornWorker \
       --proxy-allow-from '*' \
       --forwarded-allow-ips '*' \
       --bind 0.0.0.0:8000  \
       -p /var/run/dirserver.pid \
       -c gunicorn.conf.py \
       dirserver.main:app
