services:
  angie:
    image: byoda/angie:latest
    container_name: angie
    restart: always
    pull_policy: always
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    volumes:
      - type: bind
        source: /var/log/angie/${POSTFIX}
        target: /var/log/angie
      - type: bind
        source: /var/log/byoda/${POSTFIX}
        target: /var/log/byoda
      - type: bind
        source: /byoda/${POSTFIX}
        target: /byoda
      - type: bind
        source: /etc/letsencrypt/${POSTFIX}
        target: /etc/letsencrypt
      - type: bind
        source: /etc/angie/conf.d/${POSTFIX}
        target: /etc/angie/conf.d
      - vartmpssl:/var/tmp/ssl
    ports:
      - 80:80
      - 443:443
      - 444:444

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    pull_policy: always
    env_file:
      - /home/ubuntu/byoda.env
    volumes:
      - type: bind
        source: /var/lib/postgresql/${POSTFIX}/data
        target: /var/lib/postgresql/data

  byoda-appserver:
    image: byoda/byoda-pod:${TAG}
    container_name: byoda
    restart: always
    pull_policy: always
    env_file:
      - /home/ubuntu/byoda.env
    volumes:
      - type: bind
        source: /var/log/byoda/${POSTFIX}
        target: /var/log/byoda
      - type: bind
        source: /etc/angie/conf.d/${POSTFIX}
        target: /etc/angie/conf.d
      - type: bind
        source: /byoda/${POSTFIX}
        target: /byoda
      - type: bind
        source: /var/lib/postgresql/${POSTFIX}
        target: /var/lib/postgresql
      - vartmpssl:/var/tmp/ssl

volumes:
  vartmpssl:
