ARG TAG=prod
FROM byoda/byoda-python:$TAG

LABEL org.opencontainers.image.authors="steven@byoda.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /opt/byoda

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8000/api/v1/status || exit 1

COPY . byoda-python/

CMD cd /opt/byoda/byoda-python \
    && pipenv run python3 -m gunicorn \
       -k uvicorn.workers.UvicornWorker \
       --proxy-allow-from '*' \
       --forwarded-allow-ips '*' \
       --bind 0.0.0.0:8000  \
       -p /var/run/dirserver.pid \
       --error-logfile /var/log/byoda/gunicorn-directory-error.log \
       --access-logfile /var/log/byoda/gunicorn-directory-access.log \
       -c gunicorn.conf.py \
       dirserver.main:app
