ARG TAG=latest
FROM byoda/byoda-python:$TAG

LABEL org.opencontainers.image.authors="steven@byoda.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /opt/byoda

COPY . byoda-python/

ENV PYTHONPATH=/opt/byoda/byoda-python

CMD cd /opt/byoda/byoda-python \
    && pipenv run python3 svcserver/svcworker.py \
       1> /var/log/byoda/svcworker-stdout.log \
       2> /var/log/byoda/svcworker-stderr.log
