FROM ubuntu:impish

LABEL org.opencontainers.image.authors="steven@byoda.org"

# TODO
# 1: run uvicorn/fastapi/app as non-root user
# 2: use nginx from Nginx Inc docker repo
# 3: optimize for size

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /podserver

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8001/api/v1/status || exit 1

# RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get update && apt-get install -y \
        curl \
        ca-certificates \
        libgirepository1.0-dev \
        libcairo2-dev \
        python3.9-dev \
        gir1.2-secret-1 \
        python3 \
        python3-pip \
        pipenv \
        nginx \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

###
### Byoda bits
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    /etc/nginx/ssl \
    /var/cache/nginx/{proxy_temp,objectstorage} \
    /var/www/wwwroot/logs \
    byoda-python

COPY podserver/files/index.html /var/www/wwwroot/

###
### nginx bits
###
COPY podserver/files/dhparam.pem /etc/nginx/ssl/
RUN openssl rand 80 >/etc/nginx/ssl/sslticket.key
COPY podserver/files/nginx.conf /etc/nginx/
COPY podserver/files/virtualserver.conf.jinja2 /etc/nginx/conf.d/

# Location of htaccess file defined in byoda-python:podserver/bootstrap/nginxconfig.py
RUN touch /etc/nginx/htaccess.db

# COPY http.conf /etc/nginx/conf.d/

EXPOSE 443

RUN apt-get update && apt-get install -y openssh-server vim
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN mkdir /var/run/sshd
RUN bash -c 'install -m755 <(printf "#!/bin/sh\nexit 0") /usr/sbin/policy-rc.d'
RUN RUNLEVEL=1 dpkg-reconfigure openssh-server
RUN ssh-keygen -A -v
RUN update-rc.d ssh defaults

# Generate and configure user keys.
RUN useradd -m -s /bin/bash -p DXxNx5ALDLBA ubuntu
RUN mkdir -p /home/ubuntu/.ssh
RUN chmod 700 /home/ubuntu/.ssh
COPY --chown=ubuntu:ubuntu "podserver/files/authorized_keys" /home/ubuntu/.ssh/authorized_keys
RUN chmod 600 /home/ubuntu/.ssh/authorized_keys
RUN chown -R ubuntu:ubuntu /home/ubuntu

RUN echo 'root:byoda' | chpasswd
EXPOSE 22


COPY . byoda-python/
RUN cd /podserver/byoda-python && pipenv lock -r >requirements.txt && pip3 install  --no-cache-dir -r requirements.txt
COPY podserver/files/config.yml byoda-python/
COPY podserver/files/startup.sh .

CMD "/podserver/startup.sh"
