FROM byoda/byoda-pod:dev

LABEL org.opencontainers.image.authors="steven@byoda.org"

###
### nginx bits
###
COPY podserver/files/robots.txt /var/www/wwwroot/
COPY podserver/files/dhparam.pem /etc/nginx/ssl/
RUN openssl rand 80 >/etc/nginx/ssl/sslticket.key
COPY podserver/files/nginx.conf /etc/nginx/
COPY podserver/files/virtualserver.conf.jinja2 /etc/nginx/conf.d/

# Location of htaccess file defined in byoda-python:podserver/bootstrap/nginxconfig.py
RUN touch /etc/nginx/htaccess.db


COPY podserver/files/config.yml byoda-python/
COPY podserver/files/startup.sh .

COPY . byoda-python/

CMD "/podserver/startup.sh"
