FROM ubuntu:23.04

LABEL org.opencontainers.image.authors="steven@byoda.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /opt/byoda

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8000/api/v1/status || exit 1

# RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get update && apt-get install -y \
       ubuntu-keyring \
       curl \
       ca-certificates \
       ubuntu-keyring \
       build-essential \
       python3 \
       python3-pip \
       python3-distutils \
       python3-setuptools \
       libssl-dev \
       libffi-dev \
       python3-dev \
       pipenv \
       libpq-dev \
       libaugeas0 \
       git \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

###
### Byoda bits
###
RUN mkdir -p \
    /var/log/byoda \
    byoda-python

COPY ./Pipfile ./Pipfile.lock byoda-python/
RUN cd /opt/byoda/byoda-python && pipenv install --deploy --ignore-pipfile && pipenv clean

ENV PYTHONPATH=/opt/byoda/byoda-python

COPY . byoda-python/

CMD cd /opt/byoda/byoda-python \
    && pipenv run python3 -m gunicorn \
       -k uvicorn.workers.UvicornWorker \
       --bind 0.0.0.0:8000  \
       --proxy-allow-from '*' \
       --forwarded-allow-ips '*' \
       -p /var/run/modserver.pid \
       --error-logfile /var/log/byoda/gunicorn-mod-error.log \
       --access-logfile /var/log/byoda/gunicorn-mod-access.log \
       -c gunicorn.conf.py \
       modserver.main:app
