FROM ubuntu:23.04

LABEL org.opencontainers.image.authors="steven@byoda.org"

# TODO
# 1: run uvicorn/fastapi/app as non-root user

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /podserver

###
### Byoda, nginx bits
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    /var/www/wwwroot/logs \
    byoda-python

COPY ./Pipfile ./Pipfile.lock byoda-python/

# BenTo4 is used to mux audio and video files into MPEG-DASH and HLS
# https://www.bento4.com/
RUN apt-get update && apt-get install -y \
       ubuntu-keyring \
       curl \
       ca-certificates \
       build-essential \
       python3 \
       python3-pip \
       python3-distutils \
       python3-setuptools \
       libssl-dev \
       libffi-dev \
       python3-dev \
       pipenv \
       libpq-dev \
       libnng1 \
       sqlite3 \
       libaugeas0 \
       unzip \
       curl \
       git \
    && cd /podserver/byoda-python && pipenv install --verbose --deploy --ignore-pipfile && pipenv clean \
    && apt-get --yes remove build-essential \
    && apt-get --yes autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/opt/byoda/byoda-python
