FROM ubuntu:jammy

LABEL org.opencontainers.image.authors="steven@byoda.org"

# TODO
# 1: run uvicorn/fastapi/app as non-root user
# 2: use nginx from Nginx Inc docker repo
# 3: optimize for size

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /podserver

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8000/api/v1/status || exit 1

# RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get update && apt-get install -y \
        curl \
        ca-certificates \
        build-essential \
        python3 \
        python3-distutils \
        libssl-dev \
        libffi-dev \
        python3-dev \
        libpq-dev \
        libnng1 \
        nginx \
        sqlite3 \
        libaugeas0 \
        git \
        unzip \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

# We've compiled nginx with modules such as njs
COPY --from=build nginx-1.25/nginx /usr/sbin
RUN chmod 755 /usr/sbin/nginx

COPY --from=build \
        nginx-1.25/ngx_http_brotli_filter_module.so \
        nginx-1.25/ngx_http_brotli_static_module.so \
        nginx-1.25/ngx_http_geoip2_module.so \
        nginx-1.25/ngx_http_hmac_secure_link_module.so \
        nginx-1.25/ngx_http_js_module.so \
        /usr/share/nginx/modules/

# BenTo4 is used to mux audio and video files into MPEG-DASH and HLS
# https://www.bento4.com/
RUN curl -s https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-640.x86_64-unknown-linux.zip -o bento4.zip && \
        unzip bento4.zip && \
        mkdir bento4 && \
        mv Bento4-*-linux/* bento4 && \
        rm -rf Bento4-SDK-1-6-0-640.x86_64-unknown-linux && \
        rm bento4.zip

# Get the latest pip and pipenv
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
        python3 /tmp/get-pip.py && \
        rm /tmp/get-pip.py && \
        python3 -m pip install setuptools==59.8.0 && \
        python3 -m pip install pipenv && \
        python3 -m pip cache purge

###
### Byoda, nginx bits
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    /etc/nginx/ssl \
    /var/cache/nginx/proxy_temp \
    /var/cache/nginx/objectstorage \
    /var/www/wwwroot/logs \
    byoda-python

###
### nginx bits
###
COPY podserver/files/dhparam.pem /etc/nginx/ssl/
RUN openssl rand 80 >/etc/nginx/ssl/sslticket.key
COPY podserver/files/nginx.conf /etc/nginx/
COPY podserver/files/virtualserver.conf.jinja2 /etc/nginx/conf.d/

# Location of htaccess file defined in byoda-python:podserver/bootstrap/nginxconfig.py
RUN touch /etc/nginx/htaccess.db

COPY ./Pipfile ./Pipfile.lock byoda-python/
RUN cd /podserver/byoda-python && pipenv install --deploy --ignore-pipfile && pipenv clean

COPY podserver/files/config.yml byoda-python/
COPY podserver/files/startup.sh .

COPY . byoda-python/

CMD "/podserver/startup.sh"
