FROM ubuntu:24.04
COPY --from=ghcr.io/astral-sh/uv:0.9.24 /uv /uvx /usr/local/bin/

LABEL org.opencontainers.image.authors="steven@byoda.org"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8

ENV PYTHONPATH=/podserver/byoda-python
WORKDIR /podserver

###
### Byoda
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    byoda-python \
    /opt/byoda/byoda-python

COPY ./pyproject.toml ./uv.lock /podserver/byoda-python/

RUN apt-get update && apt-get install -y \
       ubuntu-keyring \
       curl \
       ca-certificates \
       build-essential \
       python3 \
       python3-setuptools \
       libssl-dev \
       libffi-dev \
       python3-dev \
       libpq-dev \
       libnng1 \
       sqlite3 \
       libaugeas0 \
       unzip \
       curl \
       git \
    && cd /podserver/byoda-python && uv sync --frozen --no-dev \
    && apt-get --yes remove build-essential \
    && apt-get --yes autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

COPY . byoda-python/

CMD cd byoda-python \
    && nice -20 ionice -c idle uv run --no-sync python3 byotubesvr/updates_worker.py