FROM ubuntu:impish

LABEL org.opencontainers.image.authors="steven@byoda.org"

# TODO
# 1: run uvicorn/fastapi/app as non-root user
# 2: use nginx from Nginx Inc docker repo
# 3: optimize for size

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /podserver

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8000/api/v1/status || exit 1

# RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get update && apt-get install -y \
        curl \
        ca-certificates \
        python3 \
        python3-pip \
        pipenv \
        nginx \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

###
### Byoda bits
###
RUN mkdir -p \
    /var/log/byoda \
    /byoda/network-byoda.net/ \
    /etc/nginx/ssl \
    /var/cache/nginx/{proxy_temp,objectstorage} \
    /var/www/wwwroot/logs \
    byoda-python

COPY podserver/files/website/ /var/www/wwwroot/

###
### nginx bits
###
COPY podserver/files/dhparam.pem /etc/nginx/ssl/
RUN openssl rand 80 >/etc/nginx/ssl/sslticket.key
COPY podserver/files/nginx.conf /etc/nginx/
COPY podserver/files/virtualserver.conf.jinja2 /etc/nginx/conf.d/

# Location of htaccess file defined in byoda-python:podserver/bootstrap/nginxconfig.py
RUN touch /etc/nginx/htaccess.db

# COPY http.conf /etc/nginx/conf.d/

EXPOSE 443

COPY ./Pipfile ./Pipfile.lock byoda-python/

COPY . byoda-python/
RUN cd /podserver/byoda-python && pipenv install --deploy --ignore-pipfile && pipenv clean
COPY podserver/files/config.yml byoda-python/
COPY podserver/files/startup.sh .

CMD "/podserver/startup.sh"
