FROM ubuntu:jammy

LABEL org.opencontainers.image.authors="steven@byoda.org"

# TODO
# 1: run uvicorn/fastapi/app as non-root user
# 2: use nginx from Nginx Inc docker repo
# 3: optimize for size

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
WORKDIR /opt/byoda

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD curl --fail http://localhost:8010/api/v1/status || exit 1

# RUN apt-get update && apt-get install -y --no-install-recommends \
RUN apt-get update && apt-get install -y \
        curl \
        ca-certificates \
        build-essential \
        python3 \
        python3-distutils \
        libssl-dev \
        libffi-dev \
        python3-dev \
        libpq-dev \
        libaugeas0 \
        git \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
        python3 /tmp/get-pip.py && \
        rm /tmp/get-pip.py && \
        python3 -m pip install setuptools==59.8.0 && \
        python3 -m pip install pipenv && \
        python3 -m pip cache purge

###
### Byoda bits
###
RUN mkdir -p \
    /var/log/byoda \
    byoda-python

COPY ./Pipfile ./Pipfile.lock byoda-python/
RUN cd /opt/byoda/byoda-python && pipenv install --deploy --ignore-pipfile && pipenv clean

ENV PYTHONPATH=/opt/byoda/byoda-python

COPY . byoda-python/

CMD  cd /opt/byoda/byoda-python && \
    pipenv run python3 -m gunicorn \
        -k uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:8000  \
        --proxy-allow-from '*' \
        --forwarded-allow-ips '*' \
        -p /var/run/dirserver.pid \
        --error-logfile /var/log/byoda/gunicorn-service-error.log \
        --access-logfile /var/log/byoda/gunicorn-service-access.log \
        -c gunicorn.conf.py \
        svcserver.main:app
