    log_format json_combined escape=json
    '{'
        '"origin": "$http_origin",'
        '"msec": $msec,'
        '"host": "$hostname",'
        '"logtime": "$time_iso8601",'
        '"remote_addr": "$remote_addr",'
        '"request": "$uri",'
        '"query_parameters": "$query_string",'
        '"request_verb": "$request_method",'
        '"responsestatus": "$status",'
        '"scheme": "$scheme",'
        '"httpversion": "$server_protocol",'
        '"request_time": $request_time,'
        '"requests": $connection_requests,'
        '"tcpinfo_rtt": $tcpinfo_rtt,'
        '"tcpinfo_rttvar": $tcpinfo_rttvar,'
        '"tcpinfo_snd_cwnd": $tcpinfo_snd_cwnd,'
        '"tcpinfo_rcv_space": $tcpinfo_rcv_space,'
        '"ssl_protocol": "$ssl_protocol",'
        '"ssl_client_s_dn": "$ssl_client_s_dn",'
        '"ssl_client_verify": "$ssl_client_verify",'
        '"ssl_client_v_remain": "$ssl_client_v_remain",'
        '"ssl_session_reused": "$ssl_session_reused",'
        '"ssl_session_id": "$ssl_session_id",'
        '"user_agent": "$http_user_agent",'
        '"referer": "$http_referer",'
        '"servername": "$server_name",'
        '"bytes": $body_bytes_sent,'
        '"upstreamipaddress": "$upstream_addr",'
        '"upstreamresponsestatus": "$upstream_status",'
        '"upstreamresponsetime": "$upstream_response_time",'
        '"upstream_cache_status": "$upstream_cache_status"'
    '}';
    access_log /var/log/angie/access.log json_combined buffer=4k;
    error_log /var/log/angie/error.log;