#!/usr/bin/env python3


'''
Tool to debug issues with the code generated by the GraphQL jinja2 template

:maintainer : Steven Hessing <steven@byoda.org>
:copyright  : Copyright 2021, 2022, 2023
:license    : GPLv3
'''

import sys

from byoda.util.logger import Logger

from podserver.codegen.service_4294929430_graphql import get_schema


def main(args):
    schema = get_schema()


if __name__ == '__main__':
    _LOGGER = Logger.getLogger(sys.argv[0], debug=True, json_out=False)
    main(sys.argv[1:])
